SWP391_G1/SWP391_G1/Pages/Admin/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.Products
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService service;
        public string filePath { get; set; } = default!;
        [BindProperty(SupportsGet =true)]
        public string ProductDescription { get; set; }
        public string ErrorValidImage { get; set; }
        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context, FlieUploadService _service)
        {
            _context = context;
            service = _service;
        }

        public IActionResult OnGet()
        {
            ViewData["CateId"] = new SelectList(_context.ServiceCategories, "Id", "CateName");
            return Page();
        }


        [BindProperty(SupportsGet = true)]
        public Product ProductCategory { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {           
            if(file.Length > (25 * 1024 * 1024) || !file.ContentType.StartsWith("image/"))
            {
                ErrorValidImage = "Image Is Invalid.";
                return Page();
            }
            if (file != null)
            {
                filePath = await service.DriveUploadBasic(file);
                ProductCategory.ProductDescription = ProductDescription;
                ProductCategory.ProductImage = filePath;
            }
            _context.Products.Add(ProductCategory);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Admin/Products/Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Products/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.Products
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService uploadservice = new FlieUploadService();
        [BindProperty(SupportsGet = true)]
        public string ProductDescription { get; set; }
        [BindProperty(SupportsGet = true)]
        public string PreImageurl { get; set; }
        public string ErrorValidImage { get; set; }
        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; } = default!;
       
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            ViewData["CateId"] = new SelectList(_context.ServiceCategories, "Id", "CateName");
            var product = await _context.Products.FirstOrDefaultAsync(m => m.ProductId == id);
            PreImageurl = "https://drive.google.com/uc?id=" + product.ProductImage;
            if (product == null)
            {
                return NotFound();
            }
            Product = product;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
            Product.ProductDescription = ProductDescription;
            if (file != null)
            {
                if (file.Length > (25 * 1024 * 1024) || !file.ContentType.StartsWith("image/"))
                {
                    ErrorValidImage = "Image Is Invalid.";
                    return Page();
                }
                bool isDelete = await uploadservice.DeleteFile(Product.ProductImage);
                var filePath = await uploadservice.DriveUploadBasic(file);
                Product.ProductImage = filePath;
            }
            _context.Attach(Product).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(Product.ProductId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ProductExists(int id)
        {
            return (_context.Products?.Any(e => e.ProductId == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Blogs/BlogDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.UserClients.Blogs
{
    public class BlogDetailModel : PageModel
    {
        public static SWP391_G1.Models.SakuraCosmeticContext context = new Models.SakuraCosmeticContext();

        PaginatedList<Comment> comments = new PaginatedList<Comment>(context.Comments.ToList(), context.Comments.Count(), 1, 6);

        [BindProperty(SupportsGet = true)]
        public int IndexPaging { get; set; } = 1;


        [BindProperty(SupportsGet = true)]
        public Comment comment { get; set; } = default;


        [BindProperty(SupportsGet = true)]
        public IList<Comment> Comments { get; set; } = default;


        [BindProperty(SupportsGet = true)]
        public Blog Blog { get; set; } = default!;


        [BindProperty]
        public string commentContext { get; set; }


        [BindProperty(SupportsGet = true)]
        public int BlogId { get; set; }

        public int TotalPage { get; set; }
        public void OnGet(int? id)
        {
            Blog = context.Blogs.FirstOrDefault(b => b.BlogId == id);

            var listComment = context.Comments.Where(c => c.BlogId == id).OrderByDescending(c=>c.Id).ToList();

            comments = new PaginatedList<Comment>(listComment, listComment.Count(), IndexPaging, 2);

            TotalPage = comments.TotalPages;

            Comments = PaginatedList<Comment>.Create(comments.AsQueryable<Comment>(), IndexPaging, 2);

            BlogId = id.Value;
        }

        public IActionResult OnPostComment()
        {
            comment = new Comment()
            {
                Comment1 = commentContext,
                UserId = HttpContext.Session.GetInt32("id"),
                BlogId = BlogId
            };
            context.Add(comment);
            context.SaveChanges();
            return RedirectToPage("/UserClients/Blogs/BlogDetail", new { id = BlogId });
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;
using System.Text.Json;

namespace SWP391_G1.Pages.UserClients.Products
{
    public class IndexModel : PageModel
    {
        public static SakuraCosmeticContext context = new SakuraCosmeticContext();
        public IndexModel (SakuraCosmeticContext _context) {
            context = _context;
        }
        //PaginatedList<Product> products = new PaginatedList<Product>(context.Products.Include(x => x.Category).ToList(), context.Products.Count(), 1, 8);
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

        public SelectList? Categories { get; set; }

        [BindProperty(SupportsGet = true)]
        public int CategoryId { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public int IndexPaging { get; set; } = 1;

        [BindProperty(Name = "id", SupportsGet = true)]
        public int Id { get; set; }

        public int TotalPage { get; set; }
        [BindProperty(SupportsGet = true)]
        public Product Product { get; set; }
        public int ProductCount { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<Category> ProductCategory { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public IList<Product> Products { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public int PageSize { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public CartDTO cart { get; set; } = default!;
        public List<CartDTO> listcarts { get; set; } = new List<CartDTO>();
        public void OnGet(int categoryId, string searchString, int indexPaging)
        {

            PaginatedList<Product> products;
            if (categoryId != 0)
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId && x.ProductStatus == 1).ToList() : context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId && x.ProductName.Contains(searchString) && x.ProductStatus == 1).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 8);
            }
            else
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).Where(x => x.ProductStatus == 1).ToList() : context.Products.Include(x => x.Category).Where(x => x.ProductName.Contains(searchString) && x.ProductStatus == 1).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 8);
            }

            TotalPage = products.TotalPages;
            List<Category> productCategory = context.Categories.ToList();
            ProductCount = context.Services.ToList().Count;
            ProductCategory = productCategory;
            ViewData["categoryList"] = productCategory;
            ViewData["CategoryId"] = new SelectList(productCategory, "CategoryId", "CategoryName");
            Products = PaginatedList<Product>.Create(products.AsQueryable<Product>(), indexPaging, 8);
        }
        public IActionResult OnPostAddToCart(int id)
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToPage("/Auth/Login");
            }
            if (HttpContext.Session.GetString("ProductCarts") == null)
            {
                cart.RecordId = 1;
                cart.DateCreated = DateTime.Now;
                cart.ProductId = id;
                cart.Count = 1;
                listcarts.Add(cart);
                HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(listcarts));
            }
            else
            {
                var oldlistcart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
                if (oldlistcart.Count <= 0)
                {
                    cart.RecordId = 1;
                    cart.DateCreated = DateTime.Now;
                    cart.ProductId = id;
                    cart.Count = 1;
                    oldlistcart.Add(cart);
                    
                }
                else
                {
                    CartDTO oldcart = oldlistcart.FirstOrDefault(x => x.ProductId == id);
                    if (oldcart != null)
                    {
                        oldcart.Count += 1;
                        cart.DateCreated = DateTime.Now;
                    }
                    else
                    {
                        cart.RecordId = oldlistcart[oldlistcart.Count - 1].RecordId + 1;
                        cart.DateCreated = DateTime.Now;
                        cart.ProductId = id;
                        cart.Count = 1;
                        oldlistcart.Add(cart);
                    }
                    
                }
                HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(oldlistcart));
            }
            return RedirectToPage("/UserClients/Products/Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Products/ProductCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SWP391_G1.Models;
using SWP391_G1.Services;
using SWP391_G1.VnPaymentService;
using System.Text.Json;

namespace SWP391_G1.Pages.UserClients.Products
{
    public class ProductCartModel : PageModel
    {
        private readonly SakuraCosmeticContext _context;
        private readonly PaymentService _vnPayService = null;
        public ProductCartModel(SakuraCosmeticContext context, PaymentService vnPayService)
        {
            _context = context;
            _vnPayService = vnPayService;
        }

        [BindProperty(SupportsGet = true)]
        public decimal total { get; set; }
        [BindProperty(SupportsGet = true)]
        public int countItem { get; set; }
        [BindProperty(SupportsGet = true)]
        public List<CartDTO> Cart { get; set; } = default!;
        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                Response.Redirect("/Auth/Login");
            }
            if (HttpContext.Session.GetString("ProductCarts") == null)
            {
                return Page();
            }
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            total = GetTotal();
            countItem = GetCount();
            HttpContext.Session.SetString("Total", total.ToString());
            ViewData["Total"] = total.ToString();
            return Page();
        }
        public async Task<IActionResult> OnPostIncreaseFromCart(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart[index].Count += 1;
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public async Task<IActionResult> OnPostRemoveFromCart(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart[index].Count -= 1;
            }
            if(Cart[index].Count == 0)
            {
                Cart.Remove(Cart[index]);
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public async Task<IActionResult> OnPostRemove(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart.Remove(Cart[index]);
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total

            decimal? total = 0;
            foreach (var item in Cart)
            {
                Product product = _context.Products.FirstOrDefault(x => x.ProductId == item.ProductId);
                total += product.ProductPrice*item.Count;
            }
            return total ?? 0;
        }
        public int GetCount()
        {
            int? count = Cart.Count;
            // Return 0 if all entries are null
            return count ?? 0;

        }
        public async Task<IActionResult> OnPostCheckout()
        {
            //-----------------------------Payment----------------------//
            HttpContext.Session.SetString("PaymentType", "Product");
            PaymentInformationModel model = new PaymentInformationModel();
            model.OrderType = "Pay Order Product";
            model.Amount = double.Parse(HttpContext.Session.GetString("Total"));
            model.OrderDescription = "Pay Order Product";
            model.Name = HttpContext.Session.GetString("username");

            string url = _vnPayService.CreatePaymentUrl(model, HttpContext);

            return Redirect(url);
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Products/Index.cshtml
@page
@model SWP391_G1.Pages.UserClients.Products.IndexModel
@{
    ViewData["Title"] = "Our Products";
    var prevDisabled = Model.IndexPaging == 1 ? "disabled" : "";
    var nextDisabled = Model.IndexPaging == Model.TotalPage ? "disabled" : "";
}
<link href="~/css/productmenu.css" rel="stylesheet" />
<div class="menu pb-3" style="background-color:#fde9f0">
    <div class="row pt-5 mb-5 me-0 ms-0">
        <div class="col-2 ms-5 me-5 ps-5">
        <h1 class="text-center ">Our Products</h1>
        </div>
        <div class="col-8 ms-5 me-5 ps-5">
            <form>
                <p>Category:</p>
                <div class="input-group mt-3">
                    <select class="form-select" asp-for="CategoryId" name="CategoryId" onchange="this.form.submit()">
                        <option value=0>All</option>
                        @foreach (var item in Model.ProductCategory)
                        {
                            <option value=@item.CategoryId>@item.CategoryName</option>
                        }
                    </select>
                </div>

                <div class="input-group mt-3">
                    <input type="search" class="form-control rounded me-1" placeholder="Search" aria-label="Search" aria-describedby="search-addon" asp-for="SearchString" />
                    <button type="submit" class="btn btn-outline-primary btn_custom">Search</button>
                </div>
              
            </form>
        </div>
    </div>
    <div class="row pe-0 me-0 ms-0">      
        <div class="col-12 list-item">
            <div class="row" style="display:flex">
                @foreach (var item in Model.Products)
                {
                    <div class="col-md-3 d-flex align-items-stretch">
                        <div class="card card-product card-plain no-shadow">
                            <div class="card-header card-header-image">
                                <img src="@item.ProductImage" alt="product Image" style="width: -webkit-fill-available;height: -webkit-fill-available;">
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">@item.ProductName</h5>                               
                            </div>
                            <div class="card-footer d-inline">
                                <div class="card-footer d-inline justify-content-between align-items-center d-flex">
                                    <span class="card-text">@item.Category.CategoryName</span>
                                    <span class="card-text">@item.ProductPrice.ToString("N0") VND</span>
                                </div>
                                <div class="d-flex justify-content-center align-items-center">
                                    <form method="post" >
                                        <input type="submit" class="btn btn-outline-primary btn_addtocart" asp-page-handler="AddToCart" asp-route-id="@item.ProductId" value="Add To Cart" style="margin-top: 10px;" />
                                    </form>                              
                                </div>
                            </div>                                                         
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="row me-0 ms-0">
        <div class="col-2 ms-5 me-5 ps-5"></div>
        <div class="col-8">
            <div class="row mt-5">
                <div class="col-12 d-flex align-items-center justify-content-center text-white">
                    <a href="/UserClients/Products/proindex?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging-1)" class="btn btn-outline-primary me-3 btn_custom btn_pre_next @prevDisabled" style="background-color:burlywood">Previous</a>
                    <a href="/UserClients/Products/proindex?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging+1)" class="btn btn-outline-primary me-3 btn_custom btn_pre_next @nextDisabled" style="background-color:burlywood">Next</a>
                    Page: @Model.IndexPaging/@Model.TotalPage
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
</div>

SWP391_G1/SWP391_G1/Pages/UserClients/Products/ProductCart.cshtml
@page
@using Microsoft.EntityFrameworkCore;
@using SWP391_G1.Models;
@model SWP391_G1.Pages.UserClients.Products.ProductCartModel
@{
    SakuraCosmeticContext context = new SakuraCosmeticContext();
}
<link href="~/css/Cart.css" rel="stylesheet" />
<div class="main-cart">
    <div class="card">
        <div class="row">
            <div class="col-md-8 cart">

                <div class="title">
                    <div class="row">
                        <div class="col"><h4><b>Cart</b></h4></div>
                        <div class="col align-self-center text-right text-muted">@Model.countItem items</div>
                    </div>
                </div>
                @foreach (var item in Model.Cart)
                {
                    Product product = context.Products.Include(x => x.Category).FirstOrDefault(x => x.ProductId == item.ProductId);
                    <div class="row border-top border-bottom">
                        <div class="main main align-items-center">
                            <div class="col-2"><img class="img-fluid" src="@product.ProductImage"></div>
                            <div class="col">
                                <div class="row text-muted">@Html.DisplayFor(modelItem => product.Category.CategoryName)</div>
                                <div class="row">@Html.DisplayFor(modelItem => product.ProductName)</div>
                            </div>
                            <div class="col">
                                <div class="btn-group" role="group" aria-label="Quantity">
                                    <form asp-page-handler="RemoveFromCart" asp-route-id="@item.RecordId" method="post">
                                        <button class="btn btn-dark">-</button>
                                    </form>
                                    <a href="#" class="">@Html.DisplayFor(modelItem => item.Count)</a>
                                    <form asp-page-handler="IncreaseFromCart" asp-route-id="@item.RecordId" method="post">
                                        <button class="btn btn-dark">+</button>
                                    </form>
                                </div>
                            </div>
                            @{
                                var totalItem = product.ProductPrice * item.Count;
                                var formattedTotal = totalItem.ToString("N0");
                            }
                            <form asp-page-handler="Remove" asp-route-id="@item.RecordId" method="post">
                                <div class="col">@Html.DisplayFor(modelItem => formattedTotal) VND &nbsp;&nbsp;<button class="btn btn-dark">&#10005;</button></div>
                            </form>
                        </div>
                    </div>
                }

                <div class="back-to-shop"><a asp-page="/Userclients/Products/Index">&leftarrow; <span class="text-muted">Back to home</span></a></div>
            </div>
            <div class="col-md-4 summary">
                <div><h5><b>Summary</b></h5></div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:0;"></div>
                </div>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    <div class="col text-right">@Model.total.ToString("N0") VND</div>
                </div>
                <form method="post" asp-page-handler="checkout">
                    <button type="submit" class="btn rounded" id="btn_checkout">Check out</button>
                </form>
            </div>
        </div>

    </div>


</div>