SWP391_G1/SWP391_G1/Models/Product.cs
using System;
using System.Collections.Generic;

namespace SWP391_G1.Models
{
    public partial class Product
    {
        public Product()
        {
            Carts = new HashSet<Cart>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int ProductId { get; set; }
        public string? ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string? ProductImage { get; set; }
        public string? ProductDescription { get; set; }
        public int? ProductStatus { get; set; }
        public int? CategoryId { get; set; }

        public virtual Category? Category { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Blogs/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;
using SWP391_G1.Services;
namespace SWP391_G1.Pages.Admin.Blogs
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService uploadservice = new FlieUploadService();
        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }
        [BindProperty(SupportsGet =true)]
        public string BlogDescription { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            ViewData["CateId"] = new SelectList(_context.BlogCategories, "Id", "CateName");
            return Page();
        }

        [BindProperty]
        public Blog Blog { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
          if (!ModelState.IsValid || _context.Blogs == null || Blog == null)
            {
                return Page();
            }
            Blog.Description = BlogDescription;
            var filePath = await uploadservice.DriveUploadBasic(file);
            Blog.BlogImageUrl = filePath;
            _context.Blogs.Add(Blog);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Blogs/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.Blogs
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService uploadservice = new FlieUploadService();
        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Blog Blog { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string BlogDescription { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog =  await _context.Blogs.Include(x => x.Cate).FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }
            Blog = blog;
           ViewData["CateId"] = new SelectList(_context.BlogCategories, "Id", "CateName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Blog.Description = BlogDescription;
            var filePath = await uploadservice.DriveUploadBasic(file);
            Blog.BlogImageUrl = filePath;
            Blog.Cate = _context.BlogCategories.FirstOrDefault(x => x.Id == Blog.CateId);
            _context.Attach(Blog).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BlogExists(Blog.BlogId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BlogExists(int id)
        {
          return (_context.Blogs?.Any(e => e.BlogId == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Employees/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.Employees
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId");
            return Page();
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Employees == null || Employee == null)
            {
                return Page();
            }

            _context.Employees.Add(Employee);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.Employees
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee =  await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            Employee = employee;
           ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Employee).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmployeeExists(Employee.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EmployeeExists(int id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ProductCategories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.ProductCategories
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Categories == null || Category == null)
            {
                return Page();
            }

            _context.Categories.Add(Category);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ProductCategories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.ProductCategories
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category =  await _context.Categories.FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Category).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(Category.CategoryId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;
using System.Linq;

namespace SWP391_G1.Pages.Admin.Products
{
    public class IndexModel : PageModel
    {
        public static SakuraCosmeticContext context;
        //PaginatedList<Service> services = new PaginatedList<Service>(context.Services.Include(x => x.Cate).ToList(), context.Services.Count(), 1, 10);
        public IndexModel(SakuraCosmeticContext _context)
        {
            context= _context;
        }
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

        public SelectList? Categories { get; set; }

        [BindProperty(SupportsGet = true)]
        public int CategoryId { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public int IndexPaging { get; set; } = 1;

        [BindProperty(Name = "id", SupportsGet = true)]
        public int Id { get; set; }

        public int TotalPage { get; set; }
        [BindProperty(SupportsGet = true)]
        public Product Product { get; set; }
        public int ProductCount { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<Category> ProductCategory { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public IList<Product> Products { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public int PageSize { get; set; } = default;
        public IActionResult OnGet(int categoryId, string searchString, int indexPaging, int pageSize)
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToPage("/Index");
            }
            PaginatedList<Product> products;
            if (pageSize == 0)
            {
                pageSize = context.Products.ToList().Count;
            }
            if (categoryId != 0)
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId).ToList() : context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId && x.ProductName.Contains(searchString)).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 3);
            }
            else
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).ToList() : context.Products.Include(x => x.Category).Where(x => x.ProductName.Contains(searchString)).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 3);
            }

            TotalPage = products.TotalPages;
            List<Category> productCategory = context.Categories.ToList();
            ProductCount = context.Products.ToList().Count;
            ProductCategory = productCategory;
            ViewData["categoryList"] = productCategory;
            ViewData["CategoryId"] = new SelectList(productCategory, "CategoryId", "CategoryName");
            Products = PaginatedList<Product>.Create(products.AsQueryable<Product>(), indexPaging, 3);

            return Page();
        }
        
        public IActionResult OnPostDisableProduct(int id)
        {
            var productToUpdate = context.Products.FirstOrDefault(x => x.ProductId == id);
            if (productToUpdate != null)
            {
                productToUpdate.ProductStatus = 0;
                context.SaveChanges();
            }
            TempData["ToastMessage"] = "Product disabled successfully.";
            TempData["ToastType"] = "success";
            return RedirectToPage("/Admin/Products/Index");
        }

        public IActionResult OnPostEnableProduct(int id)
        {
            var productToUpdate = context.Products.FirstOrDefault(x => x.ProductId == id);
            if (productToUpdate != null)
            {
                productToUpdate.ProductStatus = 1;
                context.SaveChanges();
            }
            TempData["ToastMessage"] = "Product enabled successfully.";
            TempData["ToastType"] = "success";
            return RedirectToPage("/Admin/Products/Index");
        }


    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Products/Index.cshtml
@page
@using SWP391_G1.Models;
@model SWP391_G1.Pages.Admin.Products.IndexModel
@{
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Product Management";
    var prevDisabled = Model.IndexPaging == 1 ? "disabled" : "";
    var nextDisabled = Model.IndexPaging == Model.TotalPage ? "disabled" : "";
    var toastMessage = TempData["ToastMessage"] as string;
    var toastType = TempData["ToastType"] as string;
}
<body id="page-top">
    @if (!string.IsNullOrEmpty(toastMessage))
    {
        <script>
            $(document).ready(function () {
                toastr.options = {
                    positionClass: 'toast-top-right',
                    closeButton: false
                };

                toastr.@(toastType)('@toastMessage');
            });
        </script>
    }
    <!-- Page Wrapper -->
    <div id="wrapper">

        <partial name="_SidebarAdmin" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <partial name="_TopbarAdmin" />

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h3 class="h3 mb-0 text-gray-800">Product Management</h3>

                    </div>
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="d-flex justify-content-between align-items-center" style="background-color: #f8f9fc;">
                                <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" href="/Admin/Products/Create">
                                    <i class="fas fa-plus fa-sm text-white-50"></i> Add new product
                                </a>
                                <form method="get">
                                    <div class="d-flex">
                                        <div>
                                            <select id="category" asp-for="PageSize" name="PageSize" onchange="this.form.submit()" class="form-control">
                                                <option value="@Model.ProductCount">All</option>
                                                <option value="1">1</option>
                                                <option value="3">3</option>
                                                <option value="5">5</option>
                                                <option value="7">7</option>
                                            </select>
                                        </div>
                                        <div>
                                            <span>Category:</span>
                                            <select class="form-select" asp-for="CategoryId" name="CategoryId">
                                                <option value=0>All</option>
                                                @foreach (var item in Model.ProductCategory)
                                                {
                                                    <option value=@item.CategoryId>@item.CategoryName</option>
                                                }
                                            </select>
                                        </div>
                                        <div style="margin-left:15px">
                                            Search: <input type="search" placeholder="Search" aria-label="Search" aria-describedby="search-addon" asp-for="SearchString" />
                                        </div>
                                        <button type="submit" class="btn btn-outline-primary" value="Search">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body pt-0">
                            <div class="table-responsive">

                                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Product Id</th>
                                            <th>Product Name</th>
                                            <th>Category</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Products)
                                        {
                                            <tr>
                                                <td>@item.ProductId</td>
                                                <td>@item.ProductName</td>
                                                <td>@item.Category.CategoryName</td>
                                                <td>@item.ProductPrice VND</td>
                                                @if (item.ProductStatus == 1)
                                                {
                                                    <td style="color:green">Actice</td>
                                                }
                                                else if (item.ProductStatus == 0)
                                                {
                                                    <td style="color:red">Deactive</td>
                                                }
                                                <td class="text-center">
                                                    <a type="button" class="btn btn-info" href="/Admin/Products/Edit?id=@item.ProductId">Update</a>
                                                    @if (item.ProductStatus.HasValue)
                                                    {
                                                        if (item.ProductStatus == 1 )
                                                        {
                                                            <form method="post" asp-page-handler="DisableProduct" asp-route-id="@item.ProductId">
                                                                <button type="submit" class="btn btn-danger">Disable</button>
                                                            </form>
                                                        }
                                                        else if (item.ProductStatus == 0)
                                                        {
                                                            <form method="post" asp-page-handler="EnableProduct" asp-route-id="@item.ProductId">
                                                                <button type="submit" class="btn btn-success">Enable</button>
                                                            </form>
                                                        }
                                                    }
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>
                                <div class="d-flex justify-content-between">
                                    <span>Showing @(Model.IndexPaging * 10 - 9) to @(Model.IndexPaging * 10) of @Model.ProductCount entries</span>
                                    <nav>
                                        <ul class="pagination">
                                            <li class="page-item @prevDisabled"><a class="page-link @prevDisabled" href="/Admin/Products/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging-1)&PageSize=@Model.PageSize">Previous</a></li>
                                            @for (int i = 1; i <= Model.TotalPage; i++)
                                            {
                                                <li class="page-item"><a class="page-link" href="/Admin/Products/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@i&PageSize=@Model.PageSize">@i</a></li>
                                            }
                                            <li class="page-item @nextDisabled"><a class="page-link @nextDisabled" href="/Admin/Products/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging+1)&PageSize=@Model.PageSize">Next</a></li>
                                            <li class="page-item @nextDisabled"><a class="page-link @nextDisabled" href="/Admin/Products/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging+1)&PageSize=@Model.PageSize">Next</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    @*    <div class="modal fade" id="addDoctorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
    <!-- modal-dialog-centered class -->
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="myModalLabel">Add Services</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    </div>
    </div>
    </div>*@

</body>

<script>
    $(document).ready(function () {
        // Show the modal when the button is clicked
        $("#addDoctorButton").click(function () {
            $("#addDoctorModal").modal("show");
        });
        $("#loadImage").click(function () {
            var url = $("#Image").val();
            $("#image-preview").attr("src", url);
        });
    });

</script>

<style>
    #toast-container {
        font-size: 16px;
    }

    .toast {
        font-size: 18px;
        padding: 20px;
        display: flex;
        align-items: center;
        height: 80px;
        min-width: 300px;
        max-width: 80%;
        background-color: #28a745;
        color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    tbody tr :hover {
        cursor: pointer;
    }
</style>