SWP391_G1/SWP391_G1/Models/ServiceCategory.cs
using System;
using System.Collections.Generic;

namespace SWP391_G1.Models
{
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            Services = new HashSet<Service>();
        }

        public int Id { get; set; }
        public string? CateName { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<Service> Services { get; set; }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Blogs/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;
using SWP391_G1.Services;
namespace SWP391_G1.Pages.Admin.Blogs
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService uploadservice = new FlieUploadService();
        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }
        [BindProperty(SupportsGet =true)]
        public string BlogDescription { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            ViewData["CateId"] = new SelectList(_context.BlogCategories, "Id", "CateName");
            return Page();
        }

        [BindProperty]
        public Blog Blog { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
          if (!ModelState.IsValid || _context.Blogs == null || Blog == null)
            {
                return Page();
            }
            Blog.Description = BlogDescription;
            var filePath = await uploadservice.DriveUploadBasic(file);
            Blog.BlogImageUrl = filePath;
            _context.Blogs.Add(Blog);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Blogs/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.Blogs
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService uploadservice = new FlieUploadService();
        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Blog Blog { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string BlogDescription { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog =  await _context.Blogs.Include(x => x.Cate).FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }
            Blog = blog;
           ViewData["CateId"] = new SelectList(_context.BlogCategories, "Id", "CateName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Blog.Description = BlogDescription;
            var filePath = await uploadservice.DriveUploadBasic(file);
            Blog.BlogImageUrl = filePath;
            Blog.Cate = _context.BlogCategories.FirstOrDefault(x => x.Id == Blog.CateId);
            _context.Attach(Blog).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BlogExists(Blog.BlogId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BlogExists(int id)
        {
          return (_context.Blogs?.Any(e => e.BlogId == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Employees/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.Employees
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId");
            return Page();
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Employees == null || Employee == null)
            {
                return Page();
            }

            _context.Employees.Add(Employee);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.Employees
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee =  await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            Employee = employee;
           ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Employee).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmployeeExists(Employee.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EmployeeExists(int id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ProductCategories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.ProductCategories
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Categories == null || Category == null)
            {
                return Page();
            }

            _context.Categories.Add(Category);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ProductCategories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.Admin.ProductCategories
{
    public class EditModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;

        public EditModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category =  await _context.Categories.FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Category).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(Category.CategoryId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.Products
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService service;
        public string filePath { get; set; } = default!;
        [BindProperty(SupportsGet =true)]
        public string ProductDescription { get; set; }
        public string ErrorValidImage { get; set; }
        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context, FlieUploadService _service)
        {
            _context = context;
            service = _service;
        }

        public IActionResult OnGet()
        {
            ViewData["CateId"] = new SelectList(_context.ServiceCategories, "Id", "CateName");
            return Page();
        }


        [BindProperty(SupportsGet = true)]
        public Product ProductCategory { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {           
            if(file.Length > (25 * 1024 * 1024) || !file.ContentType.StartsWith("image/"))
            {
                ErrorValidImage = "Image Is Invalid.";
                return Page();
            }
            if (file != null)
            {
                filePath = await service.DriveUploadBasic(file);
                ProductCategory.ProductDescription = ProductDescription;
                ProductCategory.ProductImage = filePath;
            }
            _context.Products.Add(ProductCategory);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Admin/Products/Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ServiceCategories/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;

namespace SWP391_G1.Pages.Admin.ServiceCategories
{
    public class IndexModel : PageModel
    {
        public static SakuraCosmeticContext context;
        public IndexModel (SakuraCosmeticContext _context) { 
            context = _context;
        }
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }
        [BindProperty(Name = "id", SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<ServiceCategory> ServiceCategory { get; set; } = default;
        public IActionResult OnGet(string searchString)
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            if (HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToPage("/Index");
            }
            var listCategories = String.IsNullOrEmpty(searchString) ? context.ServiceCategories.ToList() : context.ServiceCategories.Where(x => x.CateName.Contains(searchString)).ToList();
            ServiceCategory = listCategories;
            return Page();
        }
        public IActionResult OnPostDisableService(int id)
        {
            var serviceToUpdate = context.ServiceCategories.FirstOrDefault(x => x.Id == id);
            if (serviceToUpdate != null)
            {
                serviceToUpdate.Status = false;
                context.SaveChanges();
            }
            TempData["ToastMessage"] = "Service Category disabled successfully.";
            TempData["ToastType"] = "success";
            return RedirectToPage("/Admin/ServiceCategories/Index");
        }

        public IActionResult OnPostEnableService(int id)
        {
            var serviceToUpdate = context.ServiceCategories.FirstOrDefault(x => x.Id == id);
            if (serviceToUpdate != null)
            {
                serviceToUpdate.Status = true;
                context.SaveChanges();
            }
            TempData["ToastMessage"] = "Service Category enabled successfully.";
            TempData["ToastType"] = "success";
            return RedirectToPage("/Admin/ServiceCategories/Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/Admin/ServiceCategories/Create.cshtml
@page
@model SWP391_G1.Pages.Admin.ServiceCategories.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}
<body id="page-top">
    <div id="wrapper">

        <partial name="_SidebarAdmin" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <partial name="_TopbarAdmin" />

                <!-- Begin Page Content -->
                <div class="container-fluid">
<h1>Create</h1>

<h4>ServiceCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceCategory.CateName" class="control-label"></label>
                <input asp-for="ServiceCategory.CateName" class="form-control" />
                <span asp-validation-for="ServiceCategory.CateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="ServiceCategory.Status" type="radio" value="true">Active
                <input asp-for="ServiceCategory.Status" type="radio" value="false">Deactive
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>
</div>
</div>
</div>
</body>

SWP391_G1/SWP391_G1/Pages/Admin/ServiceCategories/Edit.cshtml
@page
@model SWP391_G1.Pages.Admin.ServiceCategories.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}
<body id="page-top">
    <div id="wrapper">

        <partial name="_SidebarAdmin" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <partial name="_TopbarAdmin" />

                <!-- Begin Page Content -->
                <div class="container-fluid">
<h1>Edit</h1>

<h4>ServiceCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ServiceCategory.Id" />
            <div class="form-group">
                <label asp-for="ServiceCategory.CateName" class="control-label"></label>
                <input asp-for="ServiceCategory.CateName" class="form-control" />
                <span asp-validation-for="ServiceCategory.CateName" class="text-danger"></span>
            </div>
                                <div class="form-group">
                                    <input asp-for="ServiceCategory.Status" type="radio" value="true">Active
                                    <input asp-for="ServiceCategory.Status" type="radio" value="false">Deactive
                                </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>
</div>
</div>
</div>
</body>

SWP391_G1/SWP391_G1/Pages/Admin/ServiceCategories/Index.cshtml
@page
@using SWP391_G1.Models;
@model SWP391_G1.Pages.Admin.ServiceCategories.IndexModel
@{
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Service Management";
    var toastMessage = TempData["ToastMessage"] as string;
    var toastType = TempData["ToastType"] as string;
}
<body id="page-top">
    @if (!string.IsNullOrEmpty(toastMessage))
    {
        <script>
            $(document).ready(function () {
                toastr.options = {
                    positionClass: 'toast-top-right',
                    closeButton: false
                };

                toastr.@(toastType)('@toastMessage');
            });
        </script>
    }
    <!-- Page Wrapper -->
    <div id="wrapper">

        <partial name="_SidebarAdmin" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <partial name="_TopbarAdmin" />

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h3 class="h3 mb-0 text-gray-800">Service Category Management</h3>

                    </div>
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="d-flex justify-content-between align-items-center" style="background-color: #f8f9fc;">
                                <a id="" href="/admin/servicecategories/create" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">

                                    <i class="fas fa-plus fa-sm text-white-50"></i> Add new service category
                                </a>
                                <form method="get">
                                    <div class="d-flex">                                        
                                        <div style="margin-left:15px">
                                            Search: <input type="search" placeholder="Search" aria-label="Search" aria-describedby="search-addon" asp-for="SearchString" />
                                        </div>
                                        <button type="submit" class="btn btn-outline-primary" value="Search">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body pt-0">
                            <div class="table-responsive">

                                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Category Id</th>
                                            <th>Category Name</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.ServiceCategory)
                                        {
                                            <tr>
                                                <td>@item.Id</td>
                                                <td>@item.CateName</td>
                                                @if (item.Status == true)
                                                {
                                                    <td style="color:green">Active</td>
                                                }
                                                else
                                                {
                                                    <td style="color:red">Deactive</td>
                                                }
                                                <td class="text-center">
                                                    <a type="button" class="btn btn-info" href="/Admin/ServiceCategories/Edit?id=@item.Id">Update</a>
                                                    @if (item.Status.HasValue)
                                                    {
                                                        if (item.Status.Value)
                                                        {
                                                            <form method="post" asp-page-handler="DisableService" asp-route-id="@item.Id">
                                                                <button type="submit" class="btn btn-danger">Disable</button>
                                                            </form>
                                                        }
                                                        else
                                                        {
                                                            <form method="post" asp-page-handler="EnableService" asp-route-id="@item.Id">
                                                                <button type="submit" class="btn btn-success">Enable</button>
                                                            </form>
                                                        }
                                                    }
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>                                
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

   

    <div class="modal fade" id="addDoctorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <!-- modal-dialog-centered class -->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Add Services</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @*<form method="post" id="addDoctorForm">
                <div class="modal-body">

                <div class="form-group">
                <label for="serviceName">Service Name:</label>
                <input type="text" class="form-control" id="serviceName" asp-for="Service.ServiceName" required>
                <span asp-validation-for="Service.ServiceName" class="text-danger"></span>
                </div>
                <div class="form-group">
                <label for="Category">Category:</label>
                <select asp-for="Service.CateId" required class="form-control" asp-items="ViewBag.CategoryId"></select>
                </div>
                <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" id="Description" asp-for="Service.Description" required>
                <span asp-validation-for="Service.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                <label for="price">Price:</label>
                <input type="number" class="form-control" id="Price" asp-for="Service.Price" required>
                <span asp-validation-for="Service.Price" class="text-danger"></span>
                </div>

                <div class="form-group">
                <label for="status">Status:</label>
                <div class="form-check">
                <input asp-for="Service.Status" class="form-check-input" type="radio" name="Service.Status" id="service-status-equal-to-0" value="0" checked>
                <label class="form-check-label" for="service-status-equal-to-0">
                Deactived
                </label>
                </div>
                <div class="form-check">
                <input asp-for="Service.Status" class="form-check-input" type="radio" name="Service.Status" id="food-status-not-equal-to-0" value="1">
                <label class="form-check-label" for="service-status-not-equal-to-0">
                Actived
                </label>
                </div>
                </div>
                <div class="form-group">
                <label for="image">Image :</label>
                <input type="text" class="form-control" id="Image" asp-for="Service.ServiceImage" required>
                <input type="button" id="loadImage" value="Load Image" class="btn btn-primary" />
                <span asp-validation-for="Service.ServiceImage" class="text-danger"></span>
                <img id="image-preview" src="" style="width:500px;height:300px">
                </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="saveDoctorButton">Add</button>
                </div>
                </form>*@
            </div>
        </div>
    </div>

</body>



<style>
    #toast-container {
        font-size: 16px;
    }

    .toast {
        font-size: 18px;
        padding: 20px;
        display: flex;
        align-items: center;
        height: 80px;
        min-width: 300px;
        max-width: 80%;
        background-color: #28a745;
        color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    tbody tr :hover {
        cursor: pointer;
    }
</style>