SWP391_G1/SWP391_G1/Pages/Admin/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391_G1.Models;
using SWP391_G1.Services;
using static System.Net.WebRequestMethods;

namespace SWP391_G1.Pages.Admin.Services
{
    public class CreateModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext _context;
        private readonly FlieUploadService service = new FlieUploadService();
        public CreateModel(SWP391_G1.Models.SakuraCosmeticContext context)
        {
            _context = context;
        }
        [BindProperty(SupportsGet =true)]
        public string fileName { get; set; }
        public string filePath { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string ServiceDescription { get; set; }
        public string ErrorValidImage { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null && HttpContext.Session.GetInt32("RoleId") != null && HttpContext.Session.GetInt32("RoleId") != 1)
            {
                return RedirectToPage("/Index");
            }
            ViewData["CateId"] = new SelectList(_context.ServiceCategories, "Id", "CateName");
            return Page();
        }

        [BindProperty(SupportsGet = true)]
        public Service Service { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
          if (!ModelState.IsValid || _context.Services == null || Service == null)
            {
                return Page();
            }
            if (file.Length > (25 * 1024 * 1024) || !file.ContentType.StartsWith("image/"))
            {
                ErrorValidImage = "Image Is Invalid.";
                return Page();
            }
            if (file != null)
            {
                fileName= file.FileName ;
                filePath = await service.DriveUploadBasic(file);
                Service.Description = ServiceDescription;
                Service.ServiceImage = filePath;
            }
            else
            {
                return Page();
            }
            _context.Services.Add(Service);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/CustomerOrder/OrderDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;

namespace SWP391_G1.Pages.UserClients.CustomerOrder
{
    
    public class OrderDetailModel : PageModel
    {
        private readonly SWP391_G1.Models.SakuraCosmeticContext context = new Models.SakuraCosmeticContext();
        [BindProperty]
        public List<OrderDetail> OrderDetail { get; set; } = default!;

        [BindProperty]
        public List<ReservationDetail> ReservationDetail { get; set; } = default!;

        public IActionResult OnGet(int? id, int? rid)
        {
            var orderdetail = context.OrderDetails.Where(o=>o.OrderId == id).Include("Product").Include("Order").ToList();

            var resevationdetail = context.ReservationDetails.Where(o => o.ReservationId == rid).Include("Reservation").Include("Service").ToList();

            OrderDetail = orderdetail;
            ReservationDetail = resevationdetail;

            return Page();
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;
using System.Text.Json;

namespace SWP391_G1.Pages.UserClients.Products
{
    public class IndexModel : PageModel
    {
        public static SakuraCosmeticContext context = new SakuraCosmeticContext();
        public IndexModel (SakuraCosmeticContext _context) {
            context = _context;
        }
        //PaginatedList<Product> products = new PaginatedList<Product>(context.Products.Include(x => x.Category).ToList(), context.Products.Count(), 1, 8);
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

        public SelectList? Categories { get; set; }

        [BindProperty(SupportsGet = true)]
        public int CategoryId { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public int IndexPaging { get; set; } = 1;

        [BindProperty(Name = "id", SupportsGet = true)]
        public int Id { get; set; }

        public int TotalPage { get; set; }
        [BindProperty(SupportsGet = true)]
        public Product Product { get; set; }
        public int ProductCount { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<Category> ProductCategory { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public IList<Product> Products { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public int PageSize { get; set; } = default;
        [BindProperty(SupportsGet = true)]
        public CartDTO cart { get; set; } = default!;
        public List<CartDTO> listcarts { get; set; } = new List<CartDTO>();
        public void OnGet(int categoryId, string searchString, int indexPaging)
        {

            PaginatedList<Product> products;
            if (categoryId != 0)
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId && x.ProductStatus == 1).ToList() : context.Products.Include(x => x.Category).Where(x => x.CategoryId == categoryId && x.ProductName.Contains(searchString) && x.ProductStatus == 1).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 8);
            }
            else
            {
                var listProduct = String.IsNullOrEmpty(searchString) ? context.Products.Include(x => x.Category).Where(x => x.ProductStatus == 1).ToList() : context.Products.Include(x => x.Category).Where(x => x.ProductName.Contains(searchString) && x.ProductStatus == 1).ToList();
                products = new PaginatedList<Product>(listProduct, listProduct.Count, 1, 8);
            }

            TotalPage = products.TotalPages;
            List<Category> productCategory = context.Categories.ToList();
            ProductCount = context.Services.ToList().Count;
            ProductCategory = productCategory;
            ViewData["categoryList"] = productCategory;
            ViewData["CategoryId"] = new SelectList(productCategory, "CategoryId", "CategoryName");
            Products = PaginatedList<Product>.Create(products.AsQueryable<Product>(), indexPaging, 8);
        }
        public IActionResult OnPostAddToCart(int id)
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToPage("/Auth/Login");
            }
            if (HttpContext.Session.GetString("ProductCarts") == null)
            {
                cart.RecordId = 1;
                cart.DateCreated = DateTime.Now;
                cart.ProductId = id;
                cart.Count = 1;
                listcarts.Add(cart);
                HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(listcarts));
            }
            else
            {
                var oldlistcart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
                if (oldlistcart.Count <= 0)
                {
                    cart.RecordId = 1;
                    cart.DateCreated = DateTime.Now;
                    cart.ProductId = id;
                    cart.Count = 1;
                    oldlistcart.Add(cart);
                    
                }
                else
                {
                    CartDTO oldcart = oldlistcart.FirstOrDefault(x => x.ProductId == id);
                    if (oldcart != null)
                    {
                        oldcart.Count += 1;
                        cart.DateCreated = DateTime.Now;
                    }
                    else
                    {
                        cart.RecordId = oldlistcart[oldlistcart.Count - 1].RecordId + 1;
                        cart.DateCreated = DateTime.Now;
                        cart.ProductId = id;
                        cart.Count = 1;
                        oldlistcart.Add(cart);
                    }
                    
                }
                HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(oldlistcart));
            }
            return RedirectToPage("/UserClients/Products/Index");
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Products/ProductCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SWP391_G1.Models;
using SWP391_G1.Services;
using SWP391_G1.VnPaymentService;
using System.Text.Json;

namespace SWP391_G1.Pages.UserClients.Products
{
    public class ProductCartModel : PageModel
    {
        private readonly SakuraCosmeticContext _context;
        private readonly PaymentService _vnPayService = null;
        public ProductCartModel(SakuraCosmeticContext context, PaymentService vnPayService)
        {
            _context = context;
            _vnPayService = vnPayService;
        }

        [BindProperty(SupportsGet = true)]
        public decimal total { get; set; }
        [BindProperty(SupportsGet = true)]
        public int countItem { get; set; }
        [BindProperty(SupportsGet = true)]
        public List<CartDTO> Cart { get; set; } = default!;
        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                Response.Redirect("/Auth/Login");
            }
            if (HttpContext.Session.GetString("ProductCarts") == null)
            {
                return Page();
            }
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            total = GetTotal();
            countItem = GetCount();
            HttpContext.Session.SetString("Total", total.ToString());
            ViewData["Total"] = total.ToString();
            return Page();
        }
        public async Task<IActionResult> OnPostIncreaseFromCart(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart[index].Count += 1;
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public async Task<IActionResult> OnPostRemoveFromCart(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart[index].Count -= 1;
            }
            if(Cart[index].Count == 0)
            {
                Cart.Remove(Cart[index]);
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public async Task<IActionResult> OnPostRemove(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<CartDTO>>(HttpContext.Session.GetString("ProductCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart.Remove(Cart[index]);
            }
            HttpContext.Session.SetString("ProductCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Products/ProductCart");
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total

            decimal? total = 0;
            foreach (var item in Cart)
            {
                Product product = _context.Products.FirstOrDefault(x => x.ProductId == item.ProductId);
                total += product.ProductPrice*item.Count;
            }
            return total ?? 0;
        }
        public int GetCount()
        {
            int? count = Cart.Count;
            // Return 0 if all entries are null
            return count ?? 0;

        }
        public async Task<IActionResult> OnPostCheckout()
        {
            //-----------------------------Payment----------------------//
            HttpContext.Session.SetString("PaymentType", "Product");
            PaymentInformationModel model = new PaymentInformationModel();
            model.OrderType = "Pay Order Product";
            model.Amount = double.Parse(HttpContext.Session.GetString("Total"));
            model.OrderDescription = "Pay Order Product";
            model.Name = HttpContext.Session.GetString("username");

            string url = _vnPayService.CreatePaymentUrl(model, HttpContext);

            return Redirect(url);
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Services/ReservationCart.cshtml.cs
using Google.Apis.Drive.v3.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SWP391_G1.Models;
using SWP391_G1.Services;
using SWP391_G1.VnPaymentService;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SWP391_G1.Pages.UserClients.Services
{
    public class ReservationCartModel : PageModel
    {
        private readonly SakuraCosmeticContext _context;
        private readonly PaymentService _vnPayService = null;
        public ReservationCartModel(SakuraCosmeticContext context, PaymentService vnPayService)
        {
            _context = context;
            _vnPayService = vnPayService;
        }

        [BindProperty(SupportsGet = true)]
        public decimal total { get; set; }
        [BindProperty(SupportsGet = true)]
        public int countItem { get; set; }
        [BindProperty(SupportsGet = true)]
        public List<ReservationCartDTO> Cart { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public DateTime dateBook { get; set; }
        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Session.GetInt32("id") == null)
            {
                Response.Redirect("/Auth/Login");
            }
            if(HttpContext.Session.GetString("ReservationCarts") == null)
            {
                return Page();
            }
            Cart = JsonSerializer.Deserialize<List<ReservationCartDTO>>(HttpContext.Session.GetString("ReservationCarts"));
            total = GetTotal();
            countItem = GetCount();
            HttpContext.Session.SetString("Total", total.ToString());
            ViewData["Total"] = total.ToString();
            return Page();
        }
        public async Task<IActionResult> OnPostUpdateDate(int? id)
        {
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart[index].ReservationTime = dateBook;
            }
            HttpContext.Session.SetString("ReservationCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Services/ReservationCart");
        }
        public async Task<IActionResult> OnPostRemove(int? id)
        {
            Cart = JsonSerializer.Deserialize<List<ReservationCartDTO>>(HttpContext.Session.GetString("ReservationCarts"));
            int index = Cart.FindIndex(x => x.RecordId == id);
            if (index != -1)
            {
                Cart.Remove(Cart[index]);
            }
            HttpContext.Session.SetString("ReservationCarts", JsonSerializer.Serialize(Cart));
            return RedirectToPage("/UserClients/Services/ReservationCart");
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total

            decimal? total = 0;
            foreach(var item in Cart)
            {
                Service service = _context.Services.FirstOrDefault(x => x.ServiceId == item.ServiceId);
                total += service.Price;
            }
            return total ?? 0;
        }
        public int GetCount()
        {
            int? count = Cart.Count;
            // Return 0 if all entries are null
            return count ?? 0;

        }
        public async Task<IActionResult> OnPostCheckout()
        {
            //-----------------------------Payment----------------------//
            HttpContext.Session.SetString("PaymentType", "Service");
            PaymentInformationModel model = new PaymentInformationModel();
            model.OrderType = "Pay Order Service";
            model.Amount = double.Parse(HttpContext.Session.GetString("Total"));
            model.OrderDescription = "Pay Order Service";
            model.Name = HttpContext.Session.GetString("username");

            string url = _vnPayService.CreatePaymentUrl(model, HttpContext);

            return Redirect(url);
        }
    }
}

SWP391_G1/SWP391_G1/Pages/UserClients/Services/Index.cshtml
@page
@using SWP391_G1.Models;
@model SWP391_G1.Pages.UserClients.Services.IndexModel
@{
    ViewData["Title"] = "Our Services";
    var prevDisabled = Model.IndexPaging == 1 ? "disabled" : "";
    var nextDisabled = Model.IndexPaging == Model.TotalPage ? "disabled" : "";
}
<link href="~/css/productmenu.css" rel="stylesheet" />
<div class="menu pb-3" style="background-color:white">
    <div class="row pt-5 mb-5 me-0 ms-0">
        <h1 class="text-center">Our Services</h1>
    </div>
    <div class="row pe-0 me-0 ms-0">
        <div class="col-2 ms-5 me-5 ps-5">
            <form>
                <p class="text-white">Category:</p>
                <div class="input-group mt-3">
                    <select class="form-select" asp-for="CategoryId" name="CategoryId" onchange="this.form.submit()">
                        <option value=0>All</option>
                        @foreach (var item in Model.ServiceCategory)
                        {
                            <option value=@item.Id>@item.CateName</option>
                        }
                    </select>
                </div>

                <div class="input-group mt-3">
                    <input type="search" class="form-control rounded me-1" placeholder="Search" aria-label="Search" aria-describedby="search-addon" asp-for="SearchString" />
                   
                </div>
                <button type="submit" class="btn btn-outline-primary btn_custom" style="margin:10px">Search</button>
            </form>
        </div>
        <div class="col-8 list-item">
            <div class="row">
                @foreach (var item in Model.Services)
                {
                    <div class="col-4 mt-2 mb-3 d-flex align-items-center justify-content-center">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="@item.ServiceImage" alt="Food Image">
                            <div class="card-body">
                                <h5 class="card-title">@item.ServiceName</h5>
                                <p class="card-text">Category: @item.Cate.CateName</p>
                                <p class="card-text">UnitPrice: @item.Price.ToString("N0")</p>
                            </div>
                            <div class="d-flex align-items-center justify-content-center mb-2">
                                <input type="button" class="btn btn-outline-primary btn_addtocart" id="addCartButton" value="Add To Cart" data-card-id="@item.ServiceId" data-bs-toggle="modal" data-bs-target="#addtoReservationCart" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-1"></div>
    </div>
    <div class="row me-0 ms-0">
        <div class="col-2 ms-5 me-5 ps-5"></div>
        <div class="col-8">
            <div class="row mt-5">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <a href="/UserClients/Services/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging-1)" class="btn btn-outline-primary me-3 btn_custom btn_pre_next @prevDisabled" style="background-color:burlywood">Previous</a>
                    <a href="/UserClients/Services/index?CategoryId=@Model.CategoryId&SearchString=@Model.SearchString&IndexPaging=@(Model.IndexPaging+1)" class="btn btn-outline-primary me-3 btn_custom btn_pre_next @nextDisabled" style="background-color:burlywood">Next</a>
                    Page: @Model.IndexPaging/@Model.TotalPage
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
</div>


<!--   Add Cart Modal    -->
<div class="modal fade" id="addtoReservationCart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <!-- modal-dialog-centered class -->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Add Services To Cart</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-page-handler="AddToCart">
            <div class="modal-body">
            <input type="hidden" id="aspForElement" asp-for="cart.ServiceId" />
            <div class="form-group">
                        <label for="reserTime">Reservation Time Book:</label>
                        <input type="datetime-local" class="form-control" id="reserTime" asp-for="cart.ReservationTime" required value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")">
            </div>
            <div class="form-group">
                        <label for="staffId">Choose staff you want:</label>
                        <select asp-for="cart.StaffId" class="form-control" asp-items="ViewBag.StaffId"></select>
            </div>

            
            </div>
            <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Add</button>
            </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // Show the modal when the button is clicked
        $("#addCartButton").click(function () {
            $("#addtoReservationCart").modal("show");
        });
        $('.btn_addtocart').click(function () {
            var serviceId = $(this).closest('.card-body').find('.card-id').text();
            console.log(serviceId);
            $('#serviceName').val(serviceId);
        });
    });

</script>
<script>
    var selectedCardId = null;

    document.querySelectorAll('.btn_addtocart').forEach(function (button) {
        button.addEventListener('click', function () {
            var cardId = this.getAttribute('data-card-id');
            selectedCardId = cardId;
            console.log(selectedCardId);
            // Gửi giá trị selectedCardId đến máy chủ hoặc thực hiện các hành động khác tùy theo yêu cầu của bạn.
            document.getElementById('aspForElement').value = cardId;
        });
    });
</script>
@*<script>
    // Lấy thời gian hiện tại
    var currentDateTime = new Date().toISOString().slice(0, 16);

    // Đặt giá trị thời gian hiện tại cho trường datetime-local
    document.getElementById("reserTime").value = currentDateTime;
</script>*@

SWP391_G1/SWP391_G1/Pages/UserClients/Services/ReservationCart.cshtml
@page
@using Microsoft.EntityFrameworkCore;
@using SWP391_G1.Models;
@model SWP391_G1.Pages.UserClients.Services.ReservationCartModel
@{
    SakuraCosmeticContext context = new SakuraCosmeticContext();
}
<link href="~/css/Cart.css" rel="stylesheet" />
<div class="main-cart">
    <div class="card">
        <div class="row">
            <div class="col-md-8 cart">

                <div class="title">
                    <div class="row">
                        <div class="col"><h4><b>Cart</b></h4></div>
                        <div class="col align-self-center text-right text-muted">@Model.countItem items</div>
                    </div>
                </div>
                @foreach (var item in Model.Cart)
                {
                    Service s = context.Services.Include(x => x.Cate).FirstOrDefault(x => x.ServiceId == item.ServiceId);
                           <div class="row border-top border-bottom">
                            <div class="main main align-items-center">
                            <div class="col-2"><img class="img-fluid" src="@s.ServiceImage"></div>
                            <div class="col">
                                <div class="row text-muted">@Html.DisplayFor(modelItem => s.Cate.CateName)</div>
                                <div class="row">@Html.DisplayFor(modelItem => s.ServiceName)</div>
                            </div>
                            @{
                                var formatPrice = s.Price.ToString("N0");
                            }
                            <div class="col">
                                <div class="row">@Html.DisplayFor(modelItem => formatPrice)</div>
                            </div>
                            <div class="col">
                                <div class="row">
                                    <form asp-page-handler="UpdateDate" asp-route-id="@item.RecordId" method="post">
                                        <input onchange="this.form.submit()" class="form-control" type="datetime-local" name="dateBook" value="@item.ReservationTime.ToString("yyyy-MM-ddTHH:mm")" />
                                    </form>
                                </div>
                            </div>
                            <form asp-page-handler="Remove" asp-route-id="@item.RecordId" method="post">
                                <div class="col"><button type="submit" class="btn btn-dark">&#10005;</button></div>
                            </form>
                        </div>
                    </div>
                }

                <div class="back-to-shop"><a asp-page="/Userclients/Services/Index">&leftarrow; <span class="text-muted">Back to home</span></a></div>
            </div>
            <div class="col-md-4 summary">
                <div><h5><b>Summary</b></h5></div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:0;"></div>
                </div>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    <div class="col text-right">@Model.total.ToString("N0") VND</div>
                </div>
                <form method="post" asp-page-handler="checkout">
                    <button type="submit" class="btn rounded" id="btn_checkout" >Check out</button>
                </form>
            </div>
        </div>

    </div>


</div>